name: Push Forms flow API to registry

on:
  workflow_dispatch:
  push:
    branches: [ self-hosted, master, develop, release/* ]
    paths:
      - "forms-flow-api/**"
      - "VERSION"

defaults:
  run:
    shell: powershell
    working-directory: ./forms-flow-api

jobs:
  build-and-push-image-to-dockerhub:
    if: github.repository == 'alanraju-aot/forms-flow-ai'
    runs-on: self-hosted

    strategy:
      matrix:
        include:
          - image: formsflow/forms-flow-webapi
            context: forms-flow-api
            dockerfile: Dockerfile
            name: forms-flow-api

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYMENT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOYMENT_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Install kubectl
        shell: powershell
        run: |
          $version = (Invoke-WebRequest `
            -Uri "https://dl.k8s.io/release/stable.txt" `
            -UseBasicParsing).Content.Trim()

          $url = "https://dl.k8s.io/release/$version/bin/windows/amd64/kubectl.exe"

          Write-Host "Downloading kubectl $version"

          Invoke-WebRequest `
            -Uri $url `
            -OutFile "$env:RUNNER_TEMP\kubectl.exe"

          New-Item `
            -ItemType Directory `
            -Force `
            -Path "$env:RUNNER_TEMP\kubectl" | Out-Null

          Move-Item `
            "$env:RUNNER_TEMP\kubectl.exe" `
            "$env:RUNNER_TEMP\kubectl\kubectl.exe" `
            -Force

          echo "$env:RUNNER_TEMP\kubectl" >> $env:GITHUB_PATH

      - name: Verify kubectl
        shell: powershell
        run: |
          kubectl version --client

      - name: Update Kube config
        shell: powershell
        run: |
          aws eks update-kubeconfig `
            --region ca-central-1 `
            --name "${{ secrets.DEV_EKS_CLUSTER }}"

      - name: Deploy to EKS
        shell: powershell
        run: |
          kubectl -n "${{ secrets.DEV_OPENSOURCE_NAMESPACE }}" patch deployment forms-flow-api -p '{"spec":{"template":{"spec":{"containers":[{"name":"forms-flow-api","image":"docker.io/formsflow/forms-flow-webapi:v8.0.0-alpha"}]}}}}'
          kubectl -n "${{ secrets.DEV_OPENSOURCE_NAMESPACE }}" rollout restart deployment forms-flow-api